//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.BLL.PaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentData", Namespace="http://schemas.datacontract.org/2004/07/BankService.Model")]
    [System.SerializableAttribute()]
    public partial class PaymentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cvv2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv2 {
            get {
                return this.Cvv2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Cvv2Field, value) != true)) {
                    this.Cvv2Field = value;
                    this.RaisePropertyChanged("Cvv2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationMonth {
            get {
                return this.ExpirationMonthField;
            }
            set {
                if ((this.ExpirationMonthField.Equals(value) != true)) {
                    this.ExpirationMonthField = value;
                    this.RaisePropertyChanged("ExpirationMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationYear {
            get {
                return this.ExpirationYearField;
            }
            set {
                if ((this.ExpirationYearField.Equals(value) != true)) {
                    this.ExpirationYearField = value;
                    this.RaisePropertyChanged("ExpirationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/BankService.Model")]
    public enum PaymentStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByVisa", ReplyAction="http://tempuri.org/IPaymentService/PayByVisaResponse")]
        GameStore.BLL.PaymentService.PaymentStatus PayByVisa(GameStore.BLL.PaymentService.PaymentData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByVisa", ReplyAction="http://tempuri.org/IPaymentService/PayByVisaResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> PayByVisaAsync(GameStore.BLL.PaymentService.PaymentData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayByMasterCardResponse")]
        GameStore.BLL.PaymentService.PaymentStatus PayByMasterCard(GameStore.BLL.PaymentService.PaymentData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayByMasterCardResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> PayByMasterCardAsync(GameStore.BLL.PaymentService.PaymentData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/Confirm", ReplyAction="http://tempuri.org/IPaymentService/ConfirmResponse")]
        GameStore.BLL.PaymentService.PaymentStatus Confirm(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/Confirm", ReplyAction="http://tempuri.org/IPaymentService/ConfirmResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> ConfirmAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : GameStore.BLL.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<GameStore.BLL.PaymentService.IPaymentService>, GameStore.BLL.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.BLL.PaymentService.PaymentStatus PayByVisa(GameStore.BLL.PaymentService.PaymentData data) {
            return base.Channel.PayByVisa(data);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> PayByVisaAsync(GameStore.BLL.PaymentService.PaymentData data) {
            return base.Channel.PayByVisaAsync(data);
        }
        
        public GameStore.BLL.PaymentService.PaymentStatus PayByMasterCard(GameStore.BLL.PaymentService.PaymentData data) {
            return base.Channel.PayByMasterCard(data);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> PayByMasterCardAsync(GameStore.BLL.PaymentService.PaymentData data) {
            return base.Channel.PayByMasterCardAsync(data);
        }
        
        public GameStore.BLL.PaymentService.PaymentStatus Confirm(string token) {
            return base.Channel.Confirm(token);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.PaymentService.PaymentStatus> ConfirmAsync(string token) {
            return base.Channel.ConfirmAsync(token);
        }
    }
}
