//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.Web.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О магазине.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый коментарий.
        /// </summary>
        public static string AddNewComment {
            get {
                return ResourceManager.GetString("AddNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить это?.
        /// </summary>
        public static string AreYouSureToDelete {
            get {
                return ResourceManager.GetString("AreYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к игре.
        /// </summary>
        public static string BackToGame {
            get {
                return ResourceManager.GetString("BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хитете заблокировать этот коментарий.
        /// </summary>
        public static string BanPromt {
            get {
                return ResourceManager.GetString("BanPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить игру.
        /// </summary>
        public static string BuyGame {
            get {
                return ResourceManager.GetString("BuyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала дешевые.
        /// </summary>
        public static string ByPriceAsc {
            get {
                return ResourceManager.GetString("ByPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала дорогие.
        /// </summary>
        public static string ByPriceDesc {
            get {
                return ResourceManager.GetString("ByPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карьера.
        /// </summary>
        public static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обучение.
        /// </summary>
        public static string CaseStudies {
            get {
                return ResourceManager.GetString("CaseStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарий был удален.
        /// </summary>
        public static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите удалить этот коментарий?.
        /// </summary>
        public static string CommentDeletePromt {
            get {
                return ResourceManager.GetString("CommentDeletePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string CommentName {
            get {
                return ResourceManager.GetString("CommentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название компании.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете вводить специальные символы (#, ?) в названии компании.
        /// </summary>
        public static string CompanyNameValidationMessage {
            get {
                return ResourceManager.GetString("CompanyNameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string ComparePasswordValidationError {
            get {
                return ResourceManager.GetString("ComparePasswordValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создан.
        /// </summary>
        public static string CreatedStatus {
            get {
                return ResourceManager.GetString("CreatedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую игру.
        /// </summary>
        public static string CreateNewGame {
            get {
                return ResourceManager.GetString("CreateNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать нового издателя.
        /// </summary>
        public static string CreateNewPublisher {
            get {
                return ResourceManager.GetString("CreateNewPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать нового пользователя.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказчик.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV2/CVC2.
        /// </summary>
        public static string CVC {
            get {
                return ResourceManager.GetString("CVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтровать по дате.
        /// </summary>
        public static string DateFilterName {
            get {
                return ResourceManager.GetString("DateFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За все время.
        /// </summary>
        public static string DateFilterViewModel_All {
            get {
                return ResourceManager.GetString("DateFilterViewModel_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок действия.
        /// </summary>
        public static string DateOfExpire {
            get {
                return ResourceManager.GetString("DateOfExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неверный формат даты.
        /// </summary>
        public static string DateValidationError {
            get {
                return ResourceManager.GetString("DateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (англ).
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (рус).
        /// </summary>
        public static string DescriptionRu {
            get {
                return ResourceManager.GetString("DescriptionRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прекращена поставка.
        /// </summary>
        public static string Discontinued {
            get {
                return ResourceManager.GetString("Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы еще ничего не положили в корзину.
        /// </summary>
        public static string DontCreateOrder {
            get {
                return ResourceManager.GetString("DontCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста.
        /// </summary>
        public static string EmptyOrder {
            get {
                return ResourceManager.GetString("EmptyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конечная дата.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидаемый формат даты например: 09/2018.
        /// </summary>
        public static string ExpireDateValidation {
            get {
                return ResourceManager.GetString("ExpireDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; имеет неверный формат даты.
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; имеет неверный формат числа.
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string Fifty {
            get {
                return ResourceManager.GetString("Fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отфильтровать.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего игр в магазине.
        /// </summary>
        public static string GameCountTitle {
            get {
                return ResourceManager.GetString("GameCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно содержать 3 и более символов.
        /// </summary>
        public static string GameFilterViewModel_NameError {
            get {
                return ResourceManager.GetString("GameFilterViewModel_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игры.
        /// </summary>
        public static string GamesTitle {
            get {
                return ResourceManager.GetString("GamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (en).
        /// </summary>
        public static string GenreNameEn {
            get {
                return ResourceManager.GetString("GenreNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название (ru).
        /// </summary>
        public static string GenreNameRu {
            get {
                return ResourceManager.GetString("GenreNameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться на главную.
        /// </summary>
        public static string GoToMain {
            get {
                return ResourceManager.GetString("GoToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string IsPersistent {
            get {
                return ResourceManager.GetString("IsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За последний месяц.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За последнюю неделю.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За последний год.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading_ru.gif.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин или пароль неверен или пользователь заблокирован.
        /// </summary>
        public static string Login_or_password_is_incorrect_or_users_is_banned {
            get {
                return ResourceManager.GetString("Login_or_password_is_incorrect_or_users_is_banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать заказ.
        /// </summary>
        public static string MakeOrder {
            get {
                return ResourceManager.GetString("MakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление сайтом.
        /// </summary>
        public static string ManageAdmin {
            get {
                return ResourceManager.GetString("ManageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная цена.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть длиннее 6 символов.
        /// </summary>
        public static string MinPasswordLength {
            get {
                return ResourceManager.GetString("MinPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная цена.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наиболее коментируемые.
        /// </summary>
        public static string MostCommented {
            get {
                return ResourceManager.GetString("MostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наиболее посещаемые.
        /// </summary>
        public static string MostViewed {
            get {
                return ResourceManager.GetString("MostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые сначала.
        /// </summary>
        public static string NewFirst {
            get {
                return ResourceManager.GetString("NewFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        public static string Newsroom {
            get {
                return ResourceManager.GetString("Newsroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств на счету.
        /// </summary>
        public static string NotEnoughtMoney {
            get {
                return ResourceManager.GetString("NotEnoughtMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой счет не найден.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string NumberSymbol {
            get {
                return ResourceManager.GetString("NumberSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 день.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 час.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string OneHundred {
            get {
                return ResourceManager.GetString("OneHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 месяц.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 неделя.
        /// </summary>
        public static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали заказа.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус заказа.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элементов на странице.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплачен.
        /// </summary>
        public static string PayedStatus {
            get {
                return ResourceManager.GetString("PayedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж успешно создан и подтвержден.
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платеж создан, ожидается подтверждение.
        /// </summary>
        public static string PaymentCreated {
            get {
                return ResourceManager.GetString("PaymentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неизвестная ошибка при платеже.
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип платежа.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы платформы.
        /// </summary>
        public static string PlatformTypes {
            get {
                return ResourceManager.GetString("PlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовить платеж.
        /// </summary>
        public static string PreparePayment {
            get {
                return ResourceManager.GetString("PreparePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; имеет неверный формат для {1}.
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; обязательно к заполнению.
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публикации.
        /// </summary>
        public static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатель.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издатели.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитировать.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитировать этот коментарий.
        /// </summary>
        public static string QuoteComment {
            get {
                return ResourceManager.GetString("QuoteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должно быть в диапазоне между {1} и {2}.
        /// </summary>
        public static string RangeValidation {
            get {
                return ResourceManager.GetString("RangeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторение пароля.
        /// </summary>
        public static string RepeatePassword {
            get {
                return ResourceManager.GetString("RepeatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответь на.
        /// </summary>
        public static string ReplyTo {
            get {
                return ResourceManager.GetString("ReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} обязательное к заполнению.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть мою корзину.
        /// </summary>
        public static string SeeBasket {
            get {
                return ResourceManager.GetString("SeeBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть коментарии.
        /// </summary>
        public static string SeeComments {
            get {
                return ResourceManager.GetString("SeeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать этот способ оплаты.
        /// </summary>
        public static string SelectPayment {
            get {
                return ResourceManager.GetString("SelectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервисы.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Shipp {
            get {
                return ResourceManager.GetString("Shipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заказа.
        /// </summary>
        public static string ShippedDate {
            get {
                return ResourceManager.GetString("ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлен.
        /// </summary>
        public static string ShippedStatus {
            get {
                return ResourceManager.GetString("ShippedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщик.
        /// </summary>
        public static string Shippers {
            get {
                return ResourceManager.GetString("Shippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная дата.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость заказа.
        /// </summary>
        public static string SumOrder {
            get {
                return ResourceManager.GetString("SumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За три года.
        /// </summary>
        public static string ThreeYear {
            get {
                return ResourceManager.GetString("ThreeYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string Twenty {
            get {
                return ResourceManager.GetString("Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За два года.
        /// </summary>
        public static string TwoYear {
            get {
                return ResourceManager.GetString("TwoYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наличии.
        /// </summary>
        public static string UnitsInStock {
            get {
                return ResourceManager.GetString("UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неверный адрес страницы.
        /// </summary>
        public static string UrlValidation {
            get {
                return ResourceManager.GetString("UrlValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество просмотров.
        /// </summary>
        public static string ViewedCount {
            get {
                return ResourceManager.GetString("ViewedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя владельца.
        /// </summary>
        public static string VisaName {
            get {
                return ResourceManager.GetString("VisaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы заблокированы и не можете писать коментарии.
        /// </summary>
        public static string YouAreBanned {
            get {
                return ResourceManager.GetString("YouAreBanned", resourceCulture);
            }
        }
    }
}
